# Generated by Django 4.2.2 on 2023-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("res_id", models.IntegerField(unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=255)),
                (
                    "rating",
                    models.FloatField(
                        blank=True, help_text="Rating out of 5", null=True
                    ),
                ),
                ("online", models.BooleanField(default=False)),
            ],
        ),
    ]
